baseURL = "https://daniellipovetsky.net"
title = "scribe ergo sum?"
languageCode = "en-us"
theme = "hugo-lithium-theme"
# disqusShortname = "username"
# googleAnalytics = ""

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/dlipovetsky"

[params]
    description = ""

    [params.logo]
    url = "logo.jpg"
    width = 50
    height = 50
    alt = "watching the sun rise over crater lake"
