baseURL = "https://daniellipovetsky.net"
title = "daniel lipovetsky"
languageCode = "en-us"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

[params]
    author = "daniel lipovetsky"
    description = ""
    githubUsername = "dlipovetsky"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "PT Sans"
    # font = "Droid Sans"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

# [[menu.icon]]
#     url = "mailto:daniel.lipovetsky@gmail.com"
#     name = "envelope-o"
#     weight = 1

 [[menu.icon]]
     url = "https://github.com/dlipovetsky/"
     name = "github"
     weight = 2

# [[menu.icon]]
#     url = "https://twitter.com/username/"
#     name = "twitter"
#     weight = 3

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "linkedin"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5
